### ISSUE TITLE
Crash and sound corruption on play-music

### ISSUE THREAD

**Issue by DexterLagan** [massung/r-cade#15]
DrRacket 7.6, Windows 10 64 bits, libsndfile 1.0.28

Running these notes crashes DrRacket right after the first few notes play :
---
#lang racket
(require r-cade)

;; create a song
(define theme
  (music "E2-E2-E2-E2."
         #:tempo 280
         #:instrument sine-wave))

(define (game-loop)
  (text 2 2 "Playing few notes.")
  (when (= (frame) 1)
    (play-music theme)))

(run game-loop 128 128)

--- 

I also had garbled sound after the first few notes of "E1-E1-E1-E1." or "E1-E1-E1-E1".

**Comment by massung** [comment]
Ugh. Well. Thanks. I'll see if I can track this down... :-)

**Comment by massung** [comment]
Fixed (finally) with db8988d7e5cc4d4c1805baff80e4773d42ef90d9.

**Comment by DexterLagan** [comment]
Awesome! Thanks!

Dex

**Comment by massung** [comment]
If curious, this was because the garbage collector was moving the underlying memory for the music out from under the music thread. If the sample data was long enough, it'd never move it (or very, very rarely). The memory is now allocated to a fixed location that the collector won't relocate.

If you happen upon this again, I'd be very surprised, but definitely re-open the issue.

**Comment by DexterLagan** [comment]
Sounds good. I’ll keep you posted.

Cheers,

Dex
